"""001_initial_schema

Revision ID: beb5cb4aa6f0
Revises: 
Create Date: 2026-08-28 15:29:33.274683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb5cb4aa6f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_security',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('consecutive_failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.String(length=64), nullable=True),
    sa.Column('last_failed_at', sa.String(length=64), nullable=True),
    sa.Column('lockout_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_account_security_email'), 'account_security', ['email'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('project_title', sa.String(length=255), nullable=True),
    sa.Column('submitted_abstract', sa.Text(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('originality_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('matched_project_id', sa.String(length=64), nullable=True),
    sa.Column('matched_project_title', sa.String(length=255), nullable=True),
    sa.Column('overlapping_keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_table('industrial_offers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('buyer_company', sa.String(length=255), nullable=False),
    sa.Column('offer_amount_inr', sa.Float(), nullable=False),
    sa.Column('proposal_type', sa.String(length=100), nullable=False),
    sa.Column('deliverables_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('counter_amount_inr', sa.Float(), nullable=True),
    sa.Column('spoc_approval', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industrial_offers_buyer_id'), 'industrial_offers', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_industrial_offers_id'), 'industrial_offers', ['id'], unique=False)
    op.create_index(op.f('ix_industrial_offers_project_id'), 'industrial_offers', ['project_id'], unique=False)
    op.create_index(op.f('ix_industrial_offers_status'), 'industrial_offers', ['status'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('is_success', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_timestamp'), 'login_attempts', ['timestamp'], unique=False)
    op.create_table('marketplace_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('seller_id', sa.String(length=64), nullable=False),
    sa.Column('seller_name', sa.String(length=255), nullable=False),
    sa.Column('seller_college', sa.String(length=255), nullable=True),
    sa.Column('seller_role', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price_inr', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('technical_specs', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('image_icon', sa.String(length=100), nullable=False),
    sa.Column('escrow_step', sa.Integer(), nullable=False),
    sa.Column('escrow_buyer_id', sa.String(length=64), nullable=True),
    sa.Column('escrow_buyer_name', sa.String(length=255), nullable=True),
    sa.Column('escrow_buyer_company', sa.String(length=255), nullable=True),
    sa.Column('escrow_status_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_items_category'), 'marketplace_items', ['category'], unique=False)
    op.create_index(op.f('ix_marketplace_items_id'), 'marketplace_items', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_items_project_id'), 'marketplace_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_marketplace_items_seller_id'), 'marketplace_items', ['seller_id'], unique=False)
    op.create_index(op.f('ix_marketplace_items_status'), 'marketplace_items', ['status'], unique=False)
    op.create_table('otp_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_requests_email'), 'otp_requests', ['email'], unique=False)
    op.create_index(op.f('ix_otp_requests_id'), 'otp_requests', ['id'], unique=False)
    op.create_index(op.f('ix_otp_requests_ip_address'), 'otp_requests', ['ip_address'], unique=False)
    op.create_index(op.f('ix_otp_requests_timestamp'), 'otp_requests', ['timestamp'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_email'), 'otp_verifications', ['email'], unique=False)
    op.create_table('password_reset_attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_attempts_email'), 'password_reset_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_attempts_id'), 'password_reset_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_attempts_ip_address'), 'password_reset_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_password_reset_attempts_timestamp'), 'password_reset_attempts', ['timestamp'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tech_stack', sa.Text(), nullable=False),
    sa.Column('repo_url', sa.String(length=512), nullable=True),
    sa.Column('demo_url', sa.String(length=512), nullable=True),
    sa.Column('bom', sa.Text(), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=False),
    sa.Column('originality_score', sa.Float(), nullable=False),
    sa.Column('similarity_index', sa.Float(), nullable=False),
    sa.Column('plagiarism_status', sa.String(length=50), nullable=False),
    sa.Column('highest_match_project_id', sa.String(length=64), nullable=True),
    sa.Column('highest_match_title', sa.String(length=255), nullable=True),
    sa.Column('top_overlapping_keywords', sa.Text(), nullable=True),
    sa.Column('college_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('team_lead_id', sa.String(length=64), nullable=False),
    sa.Column('team_lead_name', sa.String(length=255), nullable=False),
    sa.Column('faculty_mentor_id', sa.String(length=64), nullable=True),
    sa.Column('faculty_mentor_name', sa.String(length=255), nullable=True),
    sa.Column('team_members', sa.Text(), nullable=True),
    sa.Column('patent_status', sa.String(length=50), nullable=False),
    sa.Column('estimated_budget_inr', sa.Float(), nullable=False),
    sa.Column('stars_count', sa.Integer(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_college_name'), 'projects', ['college_name'], unique=False)
    op.create_index(op.f('ix_projects_domain'), 'projects', ['domain'], unique=False)
    op.create_index(op.f('ix_projects_faculty_mentor_id'), 'projects', ['faculty_mentor_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_lifecycle_status'), 'projects', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_projects_team_lead_id'), 'projects', ['team_lead_id'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('college', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_verified_academic', sa.Integer(), nullable=False),
    sa.Column('is_verified_industry', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_salt', sa.String(length=255), nullable=True),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_expires', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.String(length=64), nullable=False),
    sa.Column('last_activity', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('column', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('assignee_name', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.String(length=64), nullable=True),
    sa.Column('faculty_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_column'), 'tasks', ['column'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_column'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_team_lead_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_lifecycle_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_faculty_mentor_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_domain'), table_name='projects')
    op.drop_index(op.f('ix_projects_college_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_password_reset_attempts_timestamp'), table_name='password_reset_attempts')
    op.drop_index(op.f('ix_password_reset_attempts_ip_address'), table_name='password_reset_attempts')
    op.drop_index(op.f('ix_password_reset_attempts_id'), table_name='password_reset_attempts')
    op.drop_index(op.f('ix_password_reset_attempts_email'), table_name='password_reset_attempts')
    op.drop_table('password_reset_attempts')
    op.drop_index(op.f('ix_otp_verifications_email'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_otp_requests_timestamp'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_ip_address'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_id'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_email'), table_name='otp_requests')
    op.drop_table('otp_requests')
    op.drop_index(op.f('ix_marketplace_items_status'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_seller_id'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_project_id'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_id'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_category'), table_name='marketplace_items')
    op.drop_table('marketplace_items')
    op.drop_index(op.f('ix_login_attempts_timestamp'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_industrial_offers_status'), table_name='industrial_offers')
    op.drop_index(op.f('ix_industrial_offers_project_id'), table_name='industrial_offers')
    op.drop_index(op.f('ix_industrial_offers_id'), table_name='industrial_offers')
    op.drop_index(op.f('ix_industrial_offers_buyer_id'), table_name='industrial_offers')
    op.drop_table('industrial_offers')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_account_security_email'), table_name='account_security')
    op.drop_table('account_security')
    # ### end Alembic commands ###
